apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus 
  namespace: prometheus
spec:
  project: default
  source:
    repoURL: https://github.com/rgecan/training.git
    targetRevision: HEAD
    path: prometheus 
  destination:
    name: in-cluster
    namespace: prometheus
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
